- .github/labeler.yml
- .github/workflows/publish-formula-update.yml
> add labeler config

- .github/workflows/publish-formula-update.yml
Reverts hashicorp/homebrew-tap#16
> Revert "Update bump formula pr to use nofork"

- util/README.md
- util/lambda_trigger/lambda_trigger.go
This lambda function in the util directory will serve as the trigger to bump formula versions
> Add lambda update trigger

- Formula/consul.rb
- Formula/nomad.rb
- Formula/vault.rb
Hi!
I've backported support for `brew services` command from the main tap
> Add support for brew services

- Formula/boundary.rb
- Formula/consul.rb
- Formula/nomad.rb
- Formula/packer.rb
- Formula/terraform.rb
- Formula/vault.rb
Update formulae with template change in https://github.com/hashicorp/homebrew-tap/pull/136
> Regenerate formulae with updated template

- util/lambda_trigger/lambda_trigger.go
%s on a bool yields: "%!s(bool=false)"
%t yields: "false"
> Fix automation: properly format cask flag in event payload

- .github/workflows/publish-formula-update.yml
Use [this action](https://github.com/stefanzweifel/git-auto-commit-action) to commit updates from workflow.
> Use action to commit Formula/Cask updates

- Casks/hashicorp-boundary-desktop.rb
Ref: https://discuss.hashicorp.com/t/fresh-brew-client-install-missing-translation-for-locale-en-us/23962
> Cask: Update Boundry Desktop to 1.0.0

- Formula/consul-template.rb
- Formula/consul-terraform-sync.rb
- README.md
- util/formula_templater/config.hcl
- util/lambda_trigger/lambda_trigger.go
[Assuming the consul-template is OK and can be merged, this one can come after]
> Add consul-terraform-sync support

- Formula/consul-terraform-sync.rb
- util/formula_templater/config.hcl
Closes https://github.com/hashicorp/homebrew-tap/issues/145
> Fix Name attribute for products with spaces

- Formula/consul-aws.rb
- Formula/consul-esm.rb
- Formula/consul-k8s.rb
- Formula/envconsul.rb
This fixes https://github.com/hashicorp/homebrew-tap/pull/158 which had formatting errors in the formula files
> Fix consul-ecosystem formulas

- Formula/levant.rb
- README.md
- util/formula_templater/config.hcl
- util/lambda_trigger/lambda_trigger.go
> Add support for Levant

- Formula/nomad.rb
Updated shasums per https://releases.hashicorp.com/nomad/1.3.0/nomad_1.3.0_SHA256SUMS
> Manual bump of nomad v1.3.0

- Formula/nomad.rb
Missed a spot in https://github.com/hashicorp/homebrew-tap/pull/171
> Nomad bump 1.3.0 (for darwin)

- README.md
Slack context for internal reference: https://hashicorp.slack.com/archives/C0343CNK7T7/p1654638682893679?thread_ts=1654637610.207269&cid=C0343CNK7T7
> Update README to reflect the exclusion of prereleases

- Formula/nomad-pack.rb
- util/formula_templater/config.hcl
Update nomad-pack formula for techpreview.3.
Add support for MacOS ARM.
> Update nomad-pack formula for techpreview.3

- Casks/vagrant.rb
- README.md
- util/formula_templater/config.go
- util/formula_templater/config.hcl
- util/formula_templater/formula.go
This PR introduces support for vagrant cask for hashicorp's homebrew tap!
> RELENG-298 add support for vagrant cask

- Formula/hc-install.rb
- README.md
- util/formula_templater/config.hcl
- util/lambda_trigger/lambda_trigger.go
https://github.com/hashicorp/hc-install/releases/tag/v0.5.0
> New formula: Add `hc-install`

- Formula/boundary.rb
Have to update manually due to an automation bug that hit this build.
> update to boundary 12.1

- Formula/vault-enterprise.rb
I forgot to add vault into the path, whoops. this fixes it.
> add vault in path

- Formula/athena-cli.rb
- README.md
- util/formula_templater/config.hcl
- util/lambda_trigger/lambda_trigger.go
Add Athena-CLI (new product) to homebrew tap
> Add Athena CLI to homebrew tap

- Formula/vlt.rb
Manual update due to an automation bug that hit this build.
> update vlt to 0.1.4

- Formula/boundary-enterprise.rb
- util/formula_templater/config.hcl
- util/lambda_trigger/lambda_trigger.go
Adding Boundary-Enterprise to HashiCorp Homebrew tap
> Add boundary-enterprise to brew tap

- util/lambda_trigger/Makefile
Note, we go the extra mile to make the artifact reproducible.
This is a follow-up from #246
> Add simple command for creating release artifact

- META.d/_summary.yaml
This is a requirement for our incident response tooling migration.
[SRE2-1122](https://hashicorp.atlassian.net/browse/SRE2-1122)
[SRE2-1122]: https://hashicorp.atlassian.net/browse/SRE2-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update heimdall category to service

- Formula/tfstacks.rb
- util/formula_templater/config.hcl
Do we need to do a release or something after merging this?
Relates to https://github.com/hashicorp/releng-support/issues/209
> Fix tfstacks Formula and config

- .github/workflows/publish-homebrew-lambda.yml
Goes with https://github.com/hashicorp/releng-support/pull/220
> RELENG-1105 update homebrew lambda deploy

- Formula/vault-radar.rb
- README.md
- util/formula_templater/config.hcl
- util/lambda_trigger/lambda_trigger.go
> VAULT-25363: add vault-radar

- .github/dependabot.yml
- .github/workflows/publish-homebrew-lambda.yml
- META.d/tags.yaml
- README.md
This is a handful of miscellaneous updates related to the Heimdall entry and checks.
> Heimdall updates

- .github/workflows/publish-formula-update.yml
I also changed it to our service account instead of the older espd one that is no longer in use.
> update git config that was removed
