.github/workflows/publish-formula-update.yml
Uses the forked of action-formula-bump-pr to pass `--version` through
[Action here](https://github.com/marketplace/actions/kpenfound-fork-of-dawidd6-homebrew-bump-formula?version=v3.2.3)
=> Update to use forked formula-bump-pr

Formula/nomad.rb, Formula/packer.rb, Formula/terraform.rb, Formula/vault.rb
bump-formula-pr tries to determine the SHA, and we aren't specifically passing it to the script yet.  For the moment, take out linux support and work on getting the shas generated
=> Remove linux release support for now

util/lambda_trigger/lambda_trigger.go
formula update action can derive automatically, so we are not passing through SNS
=> remove SHASUM from event payload

util/lambda_trigger/lambda_trigger.go, util/lambda_trigger/releases.go
This has lambda to get the latest version of the product specified in the event.
It does this by querying the index.json of the product on releases.hashicorp.com and using semver to find the latest version.  We can further filter this if we want to limit by OS or Architecture.  This PR is currently filtering out enterprise and prerelease builds.
=> Lambda get latest version

.github/workflows/publish-formula-update.yml, util/lambda_trigger/lambda_trigger.go, util/lambda_trigger/lambda_trigger_test.go
This checks if the "latest" version of the product triggering the workflow is the same as the existing Formula version to avoid doing too much work.
This can happen if the trigger came from:
- Enterprise build
- Pre-release build
- Patching an older major/minor
Also update our GH actions since my forked actions have been merged
=> Update Trigger to compare Formula version

README.md
This adds an explicit list of products available in the tap and a note about Vagrant.
=> Add list of products to readme

README.md
When authenticating via SSH you need to provide the URL as well as the tap name.
=> Added correct syntax for SSH

util/formula_templater/formula.go, util/formula_templater/formula_test.go
Fixes https://github.com/hashicorp/homebrew-tap/issues/134
This changes the formula output like so:
Product has darwin_amd64 and darwin_arm64 binaries:
```
if OS.mac? && Hardware::CPU.intel?
url "https://releases.hashicorp.com/waypoint/0.2.4/waypoint_0.2.4_darwin_amd64.zip"
sha256 "bda5d7427379d8679b7475a8c04ccf522ef2bbad6c20bc3bc3ecfe7a63a075c1"
end
if OS.mac? && Hardware::CPU.arm?
url "https://releases.hashicorp.com/waypoint/0.2.4/waypoint_0.2.4_darwin_arm64.zip"
sha256 "713c73e67297fc31cfdaab26252ec4c3febef2a949353b2786af9cb21a372f9d"
end
```
Product only has darwin_amd64 binary:
```
if OS.mac?
url "https://releases.hashicorp.com/vault/1.7.0/vault_1.7.0_darwin_amd64.zip"
sha256 "374fca0c8fcde45d5710e06673d03596371e92e18c33612396484758d2967d07"
end
```
I'll regenerate the existing …
=> Provide apple silicon compat for non-arm builds

README.md
Unrelated side note: Is there a reason we prefix the cask with `hashicorp-`?
=> Add missing namespace for boundary cask

util/formula_templater/config.hcl
~Iterating on this code over at https://app.circleci.com/pipelines/github/hashicorp/terraform-releases?branch=release%2F9.9.9-sam-test-do-not-release-darwin-arm64 - there's currently a failure uploading the arm64 binary for notarization. I'll pick this up in the morning (2021-07-01).~ (this comment was intended for a different PR)
=> terraform: enable darwin/arm64 (RELENG-650)

util/lambda_trigger/lambda_trigger.go, util/lambda_trigger/lambda_trigger_test.go
Previously, while Cask support was supposed to be working, the `getFormulaVersion` wasn't actually able to see the cask version and therefore not triggering an update to casks
=> Fix update detection for casks

Formula/vault.rb
I've taken the liberty of including the download URL for the ARM64 build.
=> Including binary build for macOS arm64

util/lambda_trigger/releases.go
Sometimes the check doesn't see a new version, likely because the s3 website does some caching.  Accessing the s3 object directly should do it since the linux packaging trigger does this and does not encounter any issues.
=> fix update trigger by reading s3 directly

Formula/consul-aws.rb, Formula/consul-esm.rb, Formula/consul-k8s.rb, Formula/envconsul.rb, util/formula_templater/config.hcl
Building on https://github.com/hashicorp/homebrew-tap/pull/159, homebrew doesn't like class names in the format `ConsulAWS` vs `ConsulAws`
=> Fix consul ecosystem class names

Formula/boundary.rb, util/formula_templater/config.hcl
As of 0.7.0, ARM64 Darwin builds are published under https://releases.hashicorp.com/boundary/.
=> Add new Apple Silicon/darwin arm64 builds

util/lambda_trigger/lambda_trigger_test.go, util/lambda_trigger/releases.go
The existing lambda trigger to update formulae looks at the root releases index.json, which is a large file and may be slower to update than the product's own index.json.  Since we already know the product in this context, get the product specific index instead.
=> Improve lambda trigger to look at product specific index

Formula/nomad-pack.rb, README.md, util/formula_templater/config.hcl, util/lambda_trigger/lambda_trigger.go
This PR syncs up the tap with the current state of nomad-pack TP2 and preps for release-toolkit based future releases.
=> Add nomad-pack support

util/lambda_trigger/releases.go
We moved production artifacts to a new s3 bucket so this PR updates the URL accordingly.
=> update s3 reference to new prod bucket

util/formula_templater/config.hcl
Update the list of supported architectures across products. I manually verified these changes by cross-referencing the artifacts we're building and releasing to https://releases.hashicorp.com/ for each product listed.
Related (internal-only thread) specific to consul darwin_arm64: https://hashicorp.slack.com/archives/C0253EQ5B40/p1663782296106339?thread_ts=1663775830.923729&cid=C0253EQ5B40
=> Update list of supported architectures

.github/labeler.yml, Formula/consul-enterprise.rb, Formula/nomad-enterprise.rb, Formula/vault-enterprise.rb, README.md, util/formula_templater/config.go, util/formula_templater/config.hcl, util/formula_templater/formula.go, util/formula_templater/formula_test.go, util/formula_templater/shasums.go, util/lambda_trigger/lambda_trigger.go, util/lambda_trigger/lambda_trigger_test.go
This PR adds support for our enterprise products to the official homebrew tap. Since our enterprise products are only supported via Formula's and not Casks, no changes were made to support enterprise Casks. If/when this is needed, we'll need to make further changes. 
A few changes needed to be made to the Formula templater in formula.go,  and in the function that grabs the SHASUMS from the releases site and injects them into the ruby templates. These are needed to conform with the URL's we have at releases.hashicorp.com for enterprise products. Beyond these changes, I just followed the steps outlined in the [linux and repos and homebrew docs](https://hashicorp.atlassian.net/wiki/spaces/ENSV/pages/2157904030/Linux+Repos+and+Homebrew#Add-New-Product-Support) to create the configs for the …
=> Add Support for our ENT products

Formula/consul-dataplane.rb, util/formula_templater/config.go, util/formula_templater/config.hcl, util/formula_templater/formula.go, util/lambda_trigger/lambda_trigger.go
Adds a formula for consul-dataplane. Should not be merged until the release artifacts are ready (note: the formula is missing checksums so will need to be regenerated).
Also adds support for "recommended" dependencies, as consul-dataplane requires Envoy but users may choose to build it themselves.
=> Add consul-dataplane formula

Casks/hashicorp-boundary-desktop.rb
Release of this failed due to an issue w the homebrew lambda, short term fix here to get boundary up to date.
=> manual update of boundary desktop cask

Formula/consul-dataplane.rb
This bump won't happen automatically because pre-releases aren't supported in the tap, so it has to happen manually.
=> Bump consul-dataplane

Formula/vault-enterprise.rb
It looks like the lambda-trigger picked up the wrong vault-enterprise variant.
=> remove .hsm variant

.github/workflows/publish-formula-update.yml
This is a QoL improvement to be able to distinguish between run without needing to dig into individual workflows. This also allows us to determine what product needs action should a workflow fail before it gets to the bump step.
=> Log product info in run name

util/formula_templater/Makefile, util/formula_templater/formula_test.go, util/formula_templater/testdata/consul-enterprise.rb, util/formula_templater/testdata/consul.rb
Also, update the testdata due to the resigning that happened in #218. This process changed the 1.13.2 checksums, for reproducibility I updated the testdata to the current versions that can be pulled from git.
=> Refactor forumla_templater testdata

.github/workflows/publish-formula-update.yml
This change replaces the publish action with git commands, which gives us the ability to `git pull --rebase` before pushing changes.
This should reduce the likelyhood of race conditions when multiple formulae are automatically updated around the same time.
=> Pull and rebase before push

Casks/hashicorp-vagrant.rb
This failed to update after the latest vagrant release - possibly due to the gh tag not being updated. This quick manual fix gets them up and running while I look into the failure.
=> manual fix for vagrant 2.3.5

Casks/hashicorp-vagrant.rb
This adds a strategy that was recently added to homebrew's copy of this cask in order to prevent prerelease versions from being picked up.
=> change vagrant livecheck to gh_latest

.github/workflows/manual-publish-formula-update.yml
Failures of the SNS->lambda->GHA pipeline that triggers this workflow are fairly frequent and difficult to diagnose. This creates a manually triggered workflow to allow a user to quickly bump a product version in case of automation failure, saving time and error from the current process of manually editing brew files and opening a PR.
=> create new workflow for manually bumping product version

util/formula_templater/formula.go, util/formula_templater/formula_test.go, util/formula_templater/shasums.go
Recently the vault-enterprise HSM variant was published and this incorrectly updated the brew formula to use it. It also silently removed the digests from the files (set them to empty strings). This change forces the digests to be set.
=> Prevent publishing a formula with missing digests

.github/workflows/manual-publish-formula-update.yml, Casks/hashicorp-hashicorp-vagrant.rb
I duplicated  a cask when manually triggering a fix last week because I was unaware that the templater automatically prepended the product name with "hashicorp-". This removes that duplicate and adds a note for future maintainers.
=> Remove duplicate cask

util/lambda_trigger/lambda_trigger.go, util/lambda_trigger/lambda_trigger_test.go
This PR adds graceful handling of "new" products, that is, ones that don't have an existing cask/formula in this repository.
It also beefs up the testing of the lambda event handling.
Fixes #200
=> lambda_trigger: Support new products

CODEOWNERS, META.d/_summary.yaml, META.d/data.yml, META.d/tags.yaml
Per RELENG-639, adds heimdall compliance and fixes scope of codeowners.
=> add heimdall files and fix codeowners scope

util/lambda_trigger/Makefile, util/lambda_trigger/lambda_trigger_test.go, util/lambda_trigger/releases.go, util/lambda_trigger/testdata/releases.com_vault-enterprise_latest.json
This addresses the root cause behind mistakenly publishing vault's fips variants as the main version in #223, #206, and most recently, 64171e0a.
The Releases API does not allow us to filter by variant, so we hardcode the variant we are interested in. This restricts publishing to just our base variants of enterprise and OSS. Perhaps in the future we can revisit this to support homebrew publishing of our variants.
Related HREL-1
=> Ignore variant releases overridding core versions

README.md, util/formula_templater/config.hcl, util/lambda_trigger/lambda_trigger.go
Add tfstacks to Hashicorp Homebrew tap.
I notice most of the other PRs adding products here also create a file within the `Formula/` directory. We haven't yet released a single version of `tfstacks` so we don't have release URLs or a version number or SHA256 hashes yet. I'm not sure what the right approach here would be? Should we wait until at least one version has released before merging this, or will it just create the target file instead of updating it during the release process? Thanks!
=> Add tfstacks to brew tap

Formula/tfstacks.rb, util/formula_templater/config.hcl
To fix:
```
Error: No available formula with the name "hashicorp/tap/tfstacks". Did you mean hashicorp/tap/packer?
In formula file: /usr/local/Homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/tfstacks.rb
Expected to find class Tfstacks, but only found: TerraformStacksCLI.
```
=> class name should match the ruby file name

util/lambda_trigger/Makefile
https://hashicorp.atlassian.net/browse/RELENG-1105
Update  lambda to use the `provided.al2` runtime ahead of the go1.x EOL on December 31st.
https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/
This has been deployed locally (with the instructions from [here](https://hashicorp.atlassian.net/wiki/spaces/RELENG/pages/2157904030/Linux+Repos+and+Homebrew#There's-a-bug-in-the-lambda-and-I-have-to-update-it)), manually configured in the lambda UI as per the instructions in the link above and then tested by publishing to the topic:
`aws sns publish --topic-arn=arn:aws:sns:us-east-1:437820160095:manual-release-trigger --message='{"product": "vagrant"}'`
=>  RELENG-1105 - Migrate provided al2 runtime

Formula/enos.rb
Add enos to homebrew-tap as the bits are now open source. We'll remove enos from the internal tap here https://github.com/hashicorp/homebrew-internal/pull/60
=> Update Homebrew formula for Enos version v0.0.28

.github/dependabot.yml, .github/workflows/publish-homebrew-lambda.yml, CODEOWNERS, META.d/_summary.yaml, META.d/tags.yaml, README.md
Update CODEOWNERS for SMRE
This facilitates GH automatically selecting appropriate PR reviewers
and team discovery through Heimdall.
[skip ci]
=> Update codeowners for SMRE

util/formula_templater/config.hcl
Nomad will no longer be producing 32-bit builds of any of the ecosystem binaries. This removes them from the brew tap.
Ref: https://github.com/hashicorp/nomad-pack/pull/518
Ref: https://github.com/hashicorp/nomad/pull/23189
Ref: https://github.com/hashicorp/nomad-enterprise/issues/1053
Ref: https://github.com/hashicorp/levant/pull/541
=> No 32-bit Nomad and Nomad ecosystem builds

util/formula_templater/config.hcl
The name used currently is an invalid Ruby class name
This results in the following incorrect formula:
https://github.com/hashicorp/homebrew-tap/commit/f3d8e2ec380327287a9efabedc51a131c11ac0a6#diff-bbce9fac5595a26442059aeafb8bab526fae892f84379d558e87c6822cadea54R4
=> Fix Name in tf-migrate to be valid Ruby Class name

.github/workflows/publish-homebrew-lambda.yml
When changes are to any other code besides the lambda, we don't need to rebuild and publish it.
=> only run lambda publish when changing lambda code

.github/workflows/publish-formula-update.yml
We want to stop using the `GitHub Actions [bot]` to write to the repo and instead switch to using our releng service account. I have generated a new token under that account and have it stored as a GH secret in `HOMEBREW_TAP_UPDATER_TOKEN`. Future homebrew updates should be completed  by the `hc-github-team-es-release-engineering` service account via the associated token. 
context: https://hashicorp.slack.com/archives/C07V2JB3MEC/p1732307952353959
=> update homebrew update to use our service account

Formula/copywrite.rb
Copywrite release workflow (goreleaser) was unable to create the PR directly due to Branch Protection Rules that have been created. 
This PR has been created to manually merge the updated release version and the binaries in the copywrite file in brew.
=> Brew formula update for copywrite version v0.20.0

Casks/hashicorp-vagrant.rb
2.4.3 has been out for a few months now, but still not available via brew.
Checksums taken from:
https://releases.hashicorp.com/vagrant/2.4.3/
Similar update to the previous one:
https://github.com/hashicorp/homebrew-tap/commit/6484f2f0fef0239f027f9b1cb451e19aa39e7ae5
Fixes https://github.com/hashicorp/homebrew-tap/issues/294
=> Bump vagrant to 2.4.3

Formula/copywrite.rb
Copywrite release workflow (goreleaser) was unable to create the PR directly due to Branch Protection Rules that have been created.
This PR has been created to manually merge the updated release version and the binaries in the copywrite file in brew.
Similar PR - https://github.com/hashicorp/homebrew-tap/pull/299
=> Brew formula update for copywrite version v0.21.0

Formula/copywrite.rb
Copywrite release workflow (goreleaser) was unable to create the PR directly due to Branch Protection Rules that have been created.
This PR has been created to manually merge the updated release version and the binaries in the copywrite file in brew.
Similar to #301
=> Update `copywrite` formula for v0.22.0
